## Run analysis, write model results

## Before: assmt.csv (data)
## After:  assmt.csv (model)

library(icesTAF)

mkdir("model")

## Read assessment table
assmt <- read.taf("data/assmt.csv")

## Assign model names

## The following model names are based on visual inspection of the
## AssessmentType entries in the assmt.csv table from the SID database. When
## those entries were unclear, advice sheets were also used.
##
## Models ending with "-DLS" are used only to generate a trend index as input
## for DLS advice.

lookup <- read.table(header=TRUE, stringsAsFactors=FALSE, text='
StockKeyLabel           Method
agn.27.nea              "No assessment"
alf.27.nea              "No assessment"
ane.27.8                "CBBM"
ane.27.9a               "Gadget-DLS"
anf.27.1-2              "No assessment"
anf.27.3a46             "Survey-DLS"
ank.27.78abd            "Survey-DLS"
ank.27.8c9a             "SPiCT-DLS"
aru.27.123a4            "Survey-DLS"
aru.27.5a14             "Survey-DLS"
aru.27.5b6a             "Survey-DLS"
aru.27.6b7-1012         "Survey-DLS"
bli.27.5a14             "Survey-DLS"
bli.27.5b67             "MYCC"
bli.27.nea              "No assessment"
bll.27.22-32            "Survey-DLS"
bll.27.3a47de           "CPUE-DLS"
boc.27.6-8              "Schaefer-DLS"
bsf.27.nea              "Survey-DLS"
bsk.27.nea              "No assessment"
bss.27.4bc7ad-h         "SS3"
bss.27.6a7bj            "No assessment"
bss.27.8ab              "SS3"
bss.27.8c9a             "No assessment"
cap.27.1-2              "Age-based"
cap.27.2a514            "Age-based"
cod.21.1                "SAM"
cod.21.1a-e             "Survey-DLS"
cod.2127.1f14           "SAM"
cod.27.1-2              "SAM"
cod.27.1-2coast         "VPA-DLS"
cod.27.21               "SAM-DLS"
cod.27.22-24            "SAM"
cod.27.24-32            "SS3"
cod.27.47d20            "SAM"
cod.27.5a               "SCA"
cod.27.5b1              "SAM"
cod.27.5b2              "Survey-DLS"
cod.27.6a               "TSA"
cod.27.6b               "No assessment"
cod.27.7a               "Survey-DLS"
cod.27.7e-k             "XSA"
cyo.27.nea              "No assessment"
dab.27.22-32            "Survey-DLS"
dab.27.3a4              "Survey-DLS"
dgs.27.nea              "Age-length based"
ele.2737.nea            "Survey-DLS"
fle.27.2223             "Survey-DLS"
fle.27.2425             "Survey-DLS"
fle.27.2628             "Survey-DLS"
fle.27.2729-32          "Survey-DLS"
fle.27.3a4              "Survey-DLS"
gag.27.nea              "No assessment"
gfb.27.nea              "Survey-DLS"
ghl.27.1-2              "Gadget"
ghl.27.561214           "Biomass model"
gug.27.3a47d            "Survey-DLS"
guq.27.nea              "No assessment"
gur.27.3-8              "No assessment"
had.27.1-2              "SAM"
had.27.46a20            "TSA"
had.27.5a               "SCA"
had.27.5b               "SAM"
had.27.6b               "XSA"
had.27.7a               "ASAP"
had.27.7b-k             "ASAP"
her.27.1-24a514a        "XSA"
her.27.20-24            "SAM"
her.27.25-2932          "XSA"
her.27.28               "XSA"
her.27.3031             "SAM-DLS"
her.27.3a47d            "SAM"
her.27.5a               "ADAPT"
her.27.6a7bc            "SAM-DLS"
her.27.irls             "ASAP"
her.27.nirs             "SAM"
hke.27.3a46-8abd        "SS3"
hke.27.8c9a             "Gadget"
hom.27.2a4a5b6a7a-ce-k8 "SS3"
hom.27.3a4bc7d          "Survey-DLS"
hom.27.9a               "AMISH"
jaa.27.10a2             "No assessment"
ldb.27.7b-k8abd         "No assessment"
ldb.27.8c9a             "XSA"
lem.27.3a47d            "Survey-DLS"
lez.27.4a6a             "Biomass model"
lez.27.6b               "Survey-DLS"
lin.27.1-2              "CPUE-DLS"
lin.27.3a4a6-91214      "CPUE-DLS"
lin.27.5a               "Gadget"
lin.27.5b               "Survey-DLS"
mac.27.nea              "SAM"
meg.27.7b-k8abd         "SCA"
meg.27.8c9a             "XSA"
mon.27.78abd            "a4a"
mon.27.8c9a             "SS3"
mur.27.3a47d            "a4a-DLS"
mur.27.67a-ce-k89a      "No assessment"
nep.27.4outFU           "No assessment"
nep.27.6aoutFU          "No assessment"
nep.27.7outFU           "No assessment"
nep.fu.10               "Nephrops-DLS"
nep.fu.11               "UWTV"
nep.fu.12               "UWTV"
nep.fu.13               "UWTV"
nep.fu.14               "UWTV"
nep.fu.15               "UWTV"
nep.fu.16               "UWTV"
nep.fu.17               "UWTV"
nep.fu.19               "UWTV"
nep.fu.2021             "UWTV"
nep.fu.22               "UWTV"
nep.fu.2324             "UWTV"
nep.fu.25               "CPUE-DLS"
nep.fu.2627             "CPUE-DLS"
nep.fu.2829             "CPUE-DLS"
nep.fu.3-4              "UWTV"
nep.fu.30               "UWTV-DLS"
nep.fu.31               "CPUE-DLS"
nep.fu.32               "No assessment"
nep.fu.33               "Nephrops-DLS"
nep.fu.34               "Nephrops-DLS"
nep.fu.5                "Nephrops-DLS"
nep.fu.6                "UWTV"
nep.fu.7                "UWTV"
nep.fu.8                "UWTV"
nep.fu.9                "UWTV"
nop.27.3a4              "SAM"
nop.27.6a               "No assessment"
ory.27.nea              "No assessment"
pil.27.7                "No assessment"
pil.27.8abd             "SS3"
pil.27.8c9a             "SS3"
ple.27.21-23            "SAM"
ple.27.24-32            "SAM-DLS"
ple.27.420              "AAP"
ple.27.7a               "AAP"
ple.27.7bc              "No assessment"
ple.27.7d               "AAP"
ple.27.7e               "XSA-DLS"
ple.27.7fg              "SPiCT-DLS"
ple.27.7h-k             "XSA-DLS"
ple.27.89a              "No assessment"
pok.27.1-2              "SAM"
pok.27.3a46             "SAM"
pok.27.5a               "SCA"
pok.27.5b               "SAM"
pol.27.3a4              "No assessment"
pol.27.67               "DCAC-DLS"
pol.27.89a              "No assessment"
por.27.nea              "No assessment"
pra.27.1-2              "Biomass model"
pra.27.3a4a             "SS3"
pra.27.4a               "No assessment"
raj.27.1012             "Survey-DLS"
raj.27.3a47d            "No assessment"
raj.27.67a-ce-h         "No assessment"
raj.27.89a              "No assessment"
reb.2127.dp             "Gadget"
reb.2127.sp             "Survey-DLS"
reb.27.1-2              "SCA"
reb.27.14b              "Survey-DLS"
reb.27.5a14             "Survey-DLS"
reg.27.1-2              "Gadget"
reg.27.561214           "Gadget"
rhg.27.nea              "No assessment"
rja.27.nea              "No assessment"
rjb.27.3a4              "No assessment"
rjb.27.67a-ce-k         "No assessment"
rjb.27.89a              "No assessment"
rjc.27.3a47d            "Survey-DLS"
rjc.27.6                "Survey-DLS"
rjc.27.7afg             "Survey-DLS"
rjc.27.7e               "No assessment"
rjc.27.8                "Survey-DLS"
rjc.27.9a               "Survey-DLS"
rje.27.7de              "No assessment"
rje.27.7fg              "Survey-DLS"
rjf.27.67               "No assessment"
rjh.27.4a6              "No assessment"
rjh.27.4c7d             "Survey-DLS"
rjh.27.7afg             "No assessment"
rjh.27.7e               "No assessment"
rjh.27.9a               "CPUE-DLS"
rji.27.67               "No assessment"
rjm.27.3a47d            "Survey-DLS"
rjm.27.67bj             "Survey-DLS"
rjm.27.7ae-h            "Survey-DLS"
rjm.27.8                "Survey-DLS"
rjm.27.9a               "Survey-DLS"
rjn.27.3a4              "Survey-DLS"
rjn.27.678abd           "Survey-DLS"
rjn.27.8c               "Survey-DLS"
rjn.27.9a               "Survey-DLS"
rjr.27.23a4             "Survey-DLS"
rju.27.7bj              "No assessment"
rju.27.7de              "Survey-DLS"
rju.27.8ab              "No assessment"
rju.27.8c               "No assessment"
rju.27.9a               "No assessment"
rng.27.1245a8914ab      "No assessment"
rng.27.3a               "Survey-DLS"
rng.27.5a10b12ac14b     "No assessment"
rng.27.5b6712b          "No assessment"
sal.27.22-31            "Salmon"
sal.27.32               "Salmon-DLS"
sal.nac.all             "Salmon"
sal.neac.all            "Salmon"
sal.wgc.all             "Salmon"
san.27.6a               "No assessment"
san.sa.1r               "SMS"
san.sa.2r               "SMS"
san.sa.3r               "SMS"
san.sa.4                "SMS"
san.sa.5r               "No assessment"
san.sa.6                "No assessment"
san.sa.7r               "No assessment"
sbr.27.10               "Survey-DLS"
sbr.27.6-8              "No assessment"
sbr.27.9                "CPUE-DLS"
sck.27.nea              "No assessment"
sdv.27.nea              "Survey-DLS"
sho.27.67               "Survey-DLS"
sho.27.89a              "Survey-DLS"
sol.27.20-24            "SAM"
sol.27.4                "AAP"
sol.27.7a               "XSA"
sol.27.7bc              "No assessment"
sol.27.7d               "XSA-DLS"
sol.27.7e               "XSA"
sol.27.7fg              "XSA"
sol.27.7h-k             "XSA-DLS"
sol.27.8ab              "XSA"
sol.27.8c9a             "No assessment"
spr.27.22-32            "XSA"
spr.27.3a4              "SMS"
spr.27.67a-cf-k         "No assessment"
spr.27.7de              "Survey-DLS"
syc.27.3a47d            "Survey-DLS"
syc.27.67a-ce-j         "Survey-DLS"
syc.27.8abd             "Survey-DLS"
syc.27.8c9a             "Survey-DLS"
syt.27.67               "Survey-DLS"
thr.27.nea              "No assessment"
trs.27.22-32            "Trout-DLS"
tsu.27.nea              "No assessment"
tur.27.22-32            "Survey-DLS"
tur.27.3a               "Survey-DLS"
tur.27.4                "SAM"
usk.27.1-2              "CPUE-DLS"
usk.27.12ac             "No assessment"
usk.27.3a45b6a7-912b    "CPUE-DLS"
usk.27.5a14             "Gadget"
usk.27.6b               "No assessment"
whb.27.1-91214          "SAM"
whg.27.3a               "No assessment"
whg.27.47d              "SAM"
whg.27.6a               "TSA"
whg.27.6b               "No assessment"
whg.27.7a               "ASAP"
whg.27.7b-ce-k          "XSA"
whg.27.89a              "No assessment"
wit.27.3a47d            "SAM"
')

## Merge model names with assessment table
assmt <- merge(assmt, lookup)
assmt <- assmt[c("StockKeyLabel", "ExpertGroup", "SpeciesCommonName",
                 "DataCategory", "Method", "AssessmentType")]

## Write assessment table
write.taf(assmt, dir="model", quote=TRUE)
